---
  - name: "Running Flask App with Ansible"
    hosts: all
    remote_user: azureuser
    become: yes
    tasks:
    - name: Ensure python3 is at the latest version
      apt:
        name: python3
        state: latest
        update_cache: yes 
    # - name: installing python virtual environment
    #   command: python3-venv
    # - name:  Activating virtual env
    #   command:  . venv/bin/activate
    
    - name: install the package, force upgrade
      pip:
        name: pip
        executable: pip3
        state: latest
    - name: Create a destination app directory if it does not exist
      file:
        path: /home/azureuser/app/templates/e
        state: directory
        #mode: '0755'
    
    # - name: Your copy task
    #   copy: src={{ item.src }} dest= {{ item.dest }}
    #   with_items:
    #     - { src: 'requirements.txt', dest: '/home/azureuser/app/requirements.txt' }
    #     - { src: 'app.py', dest: '/home/azureuser/app/app.py'}
    #     - { src: 'main.py', dest: '/home/azureuser/app/main.py' }
    #     - { src: 'minst.py', dest: '/home/azureuser/app/minst.py' }
    #     - { src: 'model.h5', dest: '/home/azureuser/app/model.h5' }
    #     - { src: 'templates/', dest: '/home/azureuser/app/templates/' }
   
    - name: Your copy task
      ansible.builtin.file:
        src: '{{ item.src }}'
        dest: '/home/azureuser/app/{{ item.dest }}'
        state: link
        force: yes
      loop:
        - { src: 'requirements.txt', dest: 'requirements.txt'}
        - { src: 'app.py', dest: 'app.py'}
        - { src: 'main.py', dest: 'main.py' }
        - { src: 'minst.py', dest: 'minst.py' }
        - { src: 'model.h5', dest: 'model.h5' }
        - { src: 'templates/', dest: 'templates/'}
    - name: install python libraries
      pip:
        requirements: /home/azureuser/app/requirements.txt
        extra_args: --no-cache-dir
    - name: copy template systemd service config
      copy:
        src: .service
        dest: /etc/systemd/system/flask.service

    - name: Start Systemd Flask App Service 
      systemd: name=flask state=started daemon_reload=yes